### ISSUE TITLE
Lien en erreur 404 dans le README

### ISSUE THREAD

**Issue by Benoit485** [pantaflex44/kotidien#1]
Le lien pour la version web est en erreur 404. Celle ci ne semble plus exister ? 

C'est dommage je préfère les applications en version web

**Comment by pantaflex44** [comment]
Oui effectivement la version web n'a jamais été finalisée.

C'était une tentative a l'époque pour rendre Kotidien accessible à tous. J'ai privilégié le développement de la librairie Kotlib en C# (le cœur de Kotidien mais en C#) suite à une demande particulière et abandonné la tentative en ligne.

Le lien de la version web est supprimé. Merci pour la remarque 🙂
