### ISSUE TITLE
Fichier COPYRIGHT.txt manquant

### ISSUE THREAD

**Issue by Benoit485** [pantaflex44/kotidien#2]
Le fichier est manquant dans les sources pour utiliser pyinstaller tel quel

**Comment by pantaflex44** [comment]
Je viens de supprimer la ligne en défaut dans le fichier create_deb.sh
Effectivement elle ne sert plus à rien. Ca devrait fonctionner désormais.

Toutefois, ne suivant plus trop le projet je ne peux pas garantir la compilation avec les dernieres versions de Python et des dépendances :-)

**Comment by Benoit485** [comment]
Ça bloque toujours le lancement de pyinstaller

Ca semble être a la ligne 118 du fichier Kotidien.spec

**Comment by pantaflex44** [comment]
Effectivement. Bien vu!

Je vais m'attarder sérieusement sur Kotidien ce weekend.

**Comment by Benoit485** [comment]
J'arrive a le faire fonctionner en passant par docker avec les version des libs que tu donne + Pillow en 7.2.0 sinon il ya une erreur (d'ailleurs c'est le seul truc en erreur sur mon debian en utilisant les derniers packages, avec pyinstaller qui demande a virer des options)

Voila en attachement les 3 fichiers que j'utilise pour build et pouvoir le lancer (lancement dans mon debian, avec transfert du serveur x par les volumes) :
[docker-compose.yml.txt](https://github.com/user-attachments/files/17268744/docker-compose.yml.txt)
[Dockerfile.txt](https://github.com/user-attachments/files/17268745/Dockerfile.txt)
[entrypoint.sh.txt](https://github.com/user-attachments/files/17268746/entrypoint.sh.txt)

**Comment by pantaflex44** [comment]
J'ai suivi tes modifications et effectivement ça fonctionne mais quelques bugs font planter le code plus en profondeur. grrr...

Donc je viens de pousser une relative quantité de modifications pour rendre Kotidien compatible avec les versions actuelles (à ce jour) de Python et des dépendances requises.
De mon coté tout fonctionne désormais bien mieux (sous Linux tout au moins)!!!
Le code est aussi compilable sans soucis.

J'ai mis à jour le README.md ([Rubrique Contribuer / Compiler](https://github.com/pantaflex44/kotidien?tab=readme-ov-file#contribuer--compiler)) pour mieux aider dans la marche à suivre :-)

Je vais mettre à jour le SourceForge par la même.

En tout cas merci pour tes corrections!!!

**Comment by Benoit485** [comment]
C'est niquel avec les derniers version du moment

J'ai fait un repo pour compiler avec docker :

https://github.com/Benoit485/Kotidien_docker

Merci

**Comment by pantaflex44** [comment]
Super idée! 

Je viens d'ajouter un lien dans le README.md: https://github.com/pantaflex44/kotidien?tab=readme-ov-file#utiliser-un-conteneur-docker-tout-terrain-simple-et-efficace
